import type { Product } from "./types.js"

export const demoCatalog: Product[] = [
  {
    id: "prod-wok-granito-32",
    variantId: "var-wok-granito-32",
    sku: "MGC-WOK-GRANITO-32",
    title: "Wok de granito 32 cm con tapa",
    description:
      "Wok amplio para recetas diarias, salteados, huevos y preparaciones con menos aceite.",
    category: "Woks granito",
    brand: "Eter Niu Cocina",
    price: { amount: 150, currency: "USD" },
    originalPrice: { amount: 179, currency: "USD" },
    discountPercent: 16,
    promoLabel: "Producto estrella",
    stockSignal: "8 woks listos para entrega",
    bundleEligible: true,
    deliveryBadge: "Envio coordinado Ecuador",
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    capacity: "Porciones familiares",
    diameterCm: 32,
    pieces: 2,
    stoveCompatibility: "Gas, electrica y vitro segun proveedor",
    tipoCocina: "Familia y recetas",
    nivel: "Uso diario",
    bundleUseCase: "Shakshuka, arroz, salteados y huevos con menos aceite",
    careTips:
      "Usar utensilios de silicona o madera, fuego medio y esponja suave.",
    healthAngle: "Opcion sin teflon para cocinar con menos aceite.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    instagramSourceUrl: "https://www.instagram.com/p/DUhZTX2FSeo/",
    sourceUrls: [
      "https://www.instagram.com/p/DYdciw8oTmW/",
      "https://www.instagram.com/p/DV7N5cXmICF/",
      "https://www.instagram.com/p/DVXbLrPiHnd/",
      "https://www.instagram.com/p/DUhZTX2FSeo/",
      "https://www.instagram.com/p/DSIitliCMDg/",
    ],
    contentAngles: [
      "6 anos usando el wok",
      "huevo con menos aceite",
      "shakshuka en wok 32 cm",
      "tapa de vidrio templado",
    ],
    certificationStatus: "Proveedor por confirmar",
    claimNote:
      "Publicar PFOA, PFAS o PTFE solo si el proveedor entrega certificacion.",
    reorderAfterDays: 180,
    stock: 8,
    imageUrl:
      "https://placehold.co/1200x900/efe7db/1d3b2f?text=Wok+granito+32+cm",
    productUrl: "https://shop.b2b.com.ec/products/wok-granito-32cm-tapa",
    tags: [
      "wok",
      "granito",
      "32cm",
      "menos aceite",
      "no se pega",
      "shakshuka",
      "producto estrella",
    ],
  },
  {
    id: "prod-olla-granito-20",
    variantId: "var-olla-granito-20",
    sku: "MGC-OLLA-GRANITO-20",
    title: "Olla de granito 20 cm",
    description:
      "Olla compacta para el dia a dia, porciones pequenas y pruebas de no pega con limpieza facil.",
    category: "Ollas granito",
    brand: "Eter Niu Cocina",
    price: { amount: 95, currency: "USD" },
    originalPrice: { amount: 119, currency: "USD" },
    discountPercent: 20,
    promoLabel: "No se pega",
    stockSignal: "10 ollas disponibles",
    bundleEligible: true,
    deliveryBadge: "Entrega 24-48h segun ciudad",
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    capacity: "1 a 3 personas",
    diameterCm: 20,
    pieces: 1,
    stoveCompatibility: "Gas, electrica y vitro segun proveedor",
    tipoCocina: "Diario ligero",
    nivel: "Inicio saludable",
    bundleUseCase: "Salsas, huevos, queso, avena y porciones pequenas",
    careTips:
      "Evitar metal, precalentar suave y lavar cuando la olla este tibia.",
    healthAngle: "Alternativa a antiadherentes tradicionales para uso diario.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    instagramSourceUrl: "https://www.instagram.com/p/DWfKOWXhvJs/",
    sourceUrls: ["https://www.instagram.com/p/DWfKOWXhvJs/"],
    contentAngles: [
      "prueba queso y huevo",
      "no se pega",
      "limpieza facil en olla 20 cm",
    ],
    certificationStatus: "Proveedor por confirmar",
    claimNote:
      "Mantener copy educativo; no publicar claims medicos absolutos.",
    reorderAfterDays: 180,
    stock: 10,
    imageUrl:
      "https://placehold.co/1200x900/f3eadc/1d3b2f?text=Olla+granito+20+cm",
    productUrl: "https://shop.b2b.com.ec/products/olla-granito-20cm",
    tags: [
      "olla",
      "granito",
      "20cm",
      "no se pega",
      "queso",
      "limpieza facil",
      "menos aceite",
    ],
  },
  {
    id: "prod-olla-granito-24",
    variantId: "var-olla-granito-24",
    sku: "MGC-OLLA-GRANITO-24",
    title: "Olla de granito 24 cm familiar",
    description:
      "Olla familiar para porciones grandes, sopas, guisos y cocina diaria con acabado granito.",
    category: "Ollas granito",
    brand: "Eter Niu Cocina",
    price: { amount: 130, currency: "USD" },
    originalPrice: { amount: 159, currency: "USD" },
    discountPercent: 18,
    promoLabel: "Familiar",
    stockSignal: "12 ollas familiares disponibles",
    bundleEligible: true,
    deliveryBadge: "Stock confirmado",
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    capacity: "3 a 5 personas",
    diameterCm: 24,
    pieces: 1,
    stoveCompatibility: "Gas, electrica y vitro segun proveedor",
    tipoCocina: "Familia",
    nivel: "Uso diario",
    bundleUseCase: "Porciones grandes, sopas, arroz y guisos familiares",
    careTips:
      "Cocinar a fuego medio para conservar el recubrimiento por mas tiempo.",
    healthAngle:
      "Granito para familias que quieren una opcion practica sin teflon.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    instagramSourceUrl: "https://www.instagram.com/p/DVNNNRsFYj0/",
    sourceUrls: [
      "https://www.instagram.com/p/DVewP3viHey/",
      "https://www.instagram.com/p/DVNNNRsFYj0/",
    ],
    contentAngles: [
      "24 cm para porciones familiares",
      "menos aceite en olla familiar",
      "no se pega en uso diario",
    ],
    certificationStatus: "Proveedor por confirmar",
    claimNote:
      "Si se menciona libre de PFOA/PFAS/PTFE, pedir certificacion previa.",
    reorderAfterDays: 180,
    stock: 12,
    imageUrl:
      "https://placehold.co/1200x900/eee5d8/1d3b2f?text=Olla+granito+24+cm",
    productUrl: "https://shop.b2b.com.ec/products/olla-granito-24cm-familiar",
    tags: [
      "olla",
      "granito",
      "24cm",
      "familia",
      "porciones grandes",
      "menos aceite",
    ],
  },
  {
    id: "prod-set-mgc-granito",
    variantId: "var-set-mgc-granito",
    sku: "MGC-SET-GRANITO-FAMILIAR",
    title: "Set MGC ollas y sartenes de granito",
    description:
      "Linea MGC para cambiar ollas rayadas por un set de granito de uso diario.",
    category: "Sets granito",
    brand: "Eter Niu Cocina",
    price: { amount: 249, currency: "USD" },
    originalPrice: { amount: 299, currency: "USD" },
    discountPercent: 17,
    promoLabel: "Cambio saludable",
    stockSignal: "5 sets armados",
    bundleEligible: true,
    deliveryBadge: "Entrega coordinada",
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    capacity: "Cocina completa",
    pieces: 5,
    stoveCompatibility: "Gas, electrica y vitro segun proveedor",
    tipoCocina: "Casa completa",
    nivel: "Kit familiar",
    bundleUseCase: "Reemplazar ollas viejas y equipar la cocina principal",
    careTips:
      "Guardar sin raspar piezas entre si y usar protectores si se apilan.",
    healthAngle:
      "Set de granito para cocinar todos los dias con menos preocupacion.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    instagramSourceUrl: "https://www.instagram.com/p/DU_bJI4iCTW/",
    sourceUrls: [
      "https://www.instagram.com/p/DU_bJI4iCTW/",
      "https://www.instagram.com/p/DUmeEY_FR2i/",
      "https://www.instagram.com/p/DSIitliCMDg/",
    ],
    contentAngles: [
      "cambiar ollas viejas o rayadas",
      "linea MGC granito",
      "cocina diaria con menos preocupacion",
    ],
    certificationStatus: "Proveedor por confirmar",
    claimNote:
      "Set saludable como eleccion informada, sin promesas medicas.",
    reorderAfterDays: 210,
    stock: 5,
    imageUrl:
      "https://placehold.co/1200x900/ece2d2/1d3b2f?text=Set+MGC+granito",
    productUrl: "https://shop.b2b.com.ec/products/set-mgc-ollas-sartenes-granito",
    tags: [
      "set",
      "mgc",
      "granito",
      "ollas",
      "sartenes",
      "cambio saludable",
      "cocina completa",
    ],
  },
  {
    id: "prod-sarten-wok-granito-28",
    variantId: "var-sarten-wok-granito-28",
    sku: "MGC-SARTEN-WOK-GRANITO-28",
    title: "Sarten wok granito para recetas rapidas",
    description:
      "Sarten tipo wok para huevos, vegetales y recetas rapidas con menos aceite.",
    category: "Sartenes granito",
    brand: "Eter Niu Cocina",
    price: { amount: 85, currency: "USD" },
    originalPrice: { amount: 105, currency: "USD" },
    discountPercent: 19,
    promoLabel: "Menos aceite",
    stockSignal: "14 sartenes disponibles",
    bundleEligible: true,
    deliveryBadge: "Despacho rapido",
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    capacity: "1 a 4 personas",
    diameterCm: 28,
    pieces: 1,
    stoveCompatibility: "Gas, electrica y vitro segun proveedor",
    tipoCocina: "Recetas rapidas",
    nivel: "Uso diario",
    bundleUseCase: "Huevos, vegetales, pollo y salteados de semana",
    careTips: "Usar fuego medio y evitar aerosoles que saturen la superficie.",
    healthAngle: "Pensado para cocinar ligero sin depender de mucho aceite.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    instagramSourceUrl: "https://www.instagram.com/p/DV7N5cXmICF/",
    sourceUrls: [
      "https://www.instagram.com/p/DV7N5cXmICF/",
      "https://www.instagram.com/p/DVXbLrPiHnd/",
    ],
    contentAngles: [
      "huevo sin depender de mucho aceite",
      "recetas rapidas entre semana",
      "salteados y desayuno",
    ],
    certificationStatus: "Proveedor por confirmar",
    claimNote:
      "Hablar de menos aceite como uso culinario, no como tratamiento de salud.",
    reorderAfterDays: 180,
    stock: 14,
    imageUrl:
      "https://placehold.co/1200x900/f1e4d1/1d3b2f?text=Sarten+wok+granito",
    productUrl: "https://shop.b2b.com.ec/products/sarten-wok-granito-recetas-rapidas",
    tags: [
      "sarten",
      "wok",
      "granito",
      "28cm",
      "huevo sin aceite",
      "recetas rapidas",
    ],
  },
  {
    id: "prod-utensilios-granito",
    variantId: "var-utensilios-granito",
    sku: "MGC-UTENSILIOS-CUIDADO",
    title: "Utensilios compatibles para granito",
    description:
      "Kit de utensilios suaves para cuidar ollas y sartenes de granito sin rayarlas.",
    category: "Complementos",
    brand: "Eter Niu Cocina",
    price: { amount: 28, currency: "USD" },
    originalPrice: { amount: 35, currency: "USD" },
    discountPercent: 20,
    promoLabel: "Cuida tu olla",
    stockSignal: "20 kits disponibles",
    bundleEligible: true,
    deliveryBadge: "Agregar al pedido",
    material: "Silicona y madera",
    capacity: "Kit de cuidado",
    pieces: 4,
    tipoCocina: "Complemento",
    nivel: "Cuidado",
    bundleUseCase: "Evitar rayones y alargar la vida del recubrimiento",
    careTips: "No apoyar sobre llama directa y lavar despues de cada uso.",
    healthAngle:
      "Complemento para mantener el antiadherente sin usar utensilios metalicos.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    sourceUrls: [
      "https://www.facebook.com/infintyimportsec/photos",
      "https://www.instagram.com/stories/highlights/18046750105530201/",
    ],
    contentAngles: [
      "cuidado del recubrimiento",
      "utensilios suaves para no rayar",
      "complemento recomendado tras compra",
    ],
    certificationStatus: "No aplica",
    claimNote:
      "Complemento operativo para cuidado; no usarlo como claim de salud.",
    reorderAfterDays: 120,
    stock: 20,
    imageUrl:
      "https://placehold.co/1200x900/f4eadb/1d3b2f?text=Utensilios+para+granito",
    productUrl: "https://shop.b2b.com.ec/products/utensilios-compatibles-granito",
    tags: [
      "utensilios",
      "granito",
      "silicona",
      "madera",
      "cuidado",
      "complemento",
    ],
  },
]
