import type { Product } from "./types.js";

const kitchenDefaults = {
  vertical: "cocina" as const,
  brand: "Eter Niu Cocina",
  freeShipping: true,
  paymentMethods: ["transferencia", "deuna", "payphone"],
  couponCode: "GRANITOHOY",
  deliveryBadge: "Envio gratis Ecuador",
  stoveCompatibility: "Gas, induccion y vitroceramica",
};

const wellnessDefaults = {
  vertical: "bienestar" as const,
  brand: "Eter Niu Bienestar",
  freeShipping: true,
  paymentMethods: ["transferencia", "deuna", "payphone"],
  couponCode: "BIENESTARHOY",
  deliveryBadge: "Envio gratis Ecuador",
  stoveCompatibility: "No aplica",
};

const kitchenCatalog: Product[] = [
  {
    ...kitchenDefaults,
    id: "prod-wok-granito-32",
    variantId: "var-wok-granito-32",
    sku: "MGC-WOK-GRANITO-32",
    title: "Wok 32 cm granito premium antiadherente",
    category: "Woks granito",
    description:
      "Wok de granito antiadherente para cocina diaria, salteados y porciones familiares.",
    stock: 1,
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    pfoaFree: true,
    capacity: "Porciones familiares",
    diameterCm: 32,
    pieces: 1,
    promoLabel: "Catalogo real WhatsApp",
    stockSignal: "Stock por confirmar por WhatsApp",
    deliveryBadge: "Envio gratis Ecuador",
    bundleEligible: true,
    stoveCompatibility: "Gas, induccion y vitroceramica",
    tipoCocina: "Familia y recetas",
    nivel: "Uso diario",
    bundleUseCase:
      "Salteados, arroz, recetas familiares y cocina con menos aceite",
    careTips:
      "Usar utensilios de silicona o madera, fuego medio y esponja suave.",
    healthAngle:
      "Opcion sin teflon para cocinar diario con una superficie antiadherente de granito.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    contentAngles: [
      "granito premium",
      "wok 32 cm",
      "menos aceite",
      "cocina familiar",
    ],
    certificationStatus:
      "Catalogo WhatsApp: certificaciones USA y Europeas; guardar respaldo del proveedor antes de pauta fuerte.",
    claimNote:
      "No publicar claims medicos; libre de teflon/PFOA queda sujeto a respaldo del proveedor.",
    reorderAfterDays: 180,
    tags: [
      "wok",
      "granito",
      "32cm",
      "menos aceite",
      "granito real",
      "producto estrella",
    ],
    sourceUrls: ["https://wa.me/c/593979854915"],
    price: {
      amount: 151.2,
      currency: "USD",
    },
    originalPrice: {
      amount: 151.2,
      currency: "USD",
    },
    vertical: "cocina",
    brand: "Eter Niu Cocina",
    freeShipping: true,
    paymentMethods: ["transferencia", "deuna", "payphone"],
    couponCode: "GRANITOHOY",
    imageUrl: "https://cocina.b2b.com.ec/media/photo-receta-wok.jpg",
    productUrl: "https://cocina.b2b.com.ec/products/wok-granito-32cm-tapa",
  },
  {
    ...kitchenDefaults,
    id: "prod-olla-granito-20",
    variantId: "var-olla-granito-20",
    sku: "MGC-OLLA-GRANITO-20",
    title: "Olla 20 cm Granito Premium antiadherente",
    category: "Ollas granito",
    description:
      "Olla de granito antiadherente para porciones pequenas y uso diario en casa.",
    stock: 1,
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    pfoaFree: true,
    capacity: "1 a 3 personas",
    diameterCm: 20,
    pieces: 1,
    promoLabel: "Uso diario",
    stockSignal: "Stock por confirmar por WhatsApp",
    deliveryBadge: "Envio gratis 24-48h segun ciudad",
    bundleEligible: true,
    stoveCompatibility: "Gas, induccion y vitroceramica",
    tipoCocina: "Diario ligero",
    nivel: "Inicio saludable",
    bundleUseCase: "Salsas, avena, guarniciones y porciones pequenas",
    careTips:
      "Evitar metal, precalentar suave y lavar cuando la olla este tibia.",
    healthAngle: "Alternativa a antiadherentes tradicionales para uso diario.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    contentAngles: ["olla 20 cm", "porciones pequenas", "uso diario"],
    certificationStatus:
      "Catalogo WhatsApp: certificaciones USA y Europeas; guardar respaldo del proveedor antes de pauta fuerte.",
    claimNote:
      "No publicar claims medicos; libre de teflon/PFOA queda sujeto a respaldo del proveedor.",
    reorderAfterDays: 180,
    tags: ["olla", "granito", "20cm", "uso diario", "menos aceite"],
    sourceUrls: ["https://wa.me/c/593979854915"],
    price: {
      amount: 75.6,
      currency: "USD",
    },
    originalPrice: {
      amount: 75.6,
      currency: "USD",
    },
    vertical: "cocina",
    brand: "Eter Niu Cocina",
    freeShipping: true,
    paymentMethods: ["transferencia", "deuna", "payphone"],
    couponCode: "GRANITOHOY",
    imageUrl: "https://cocina.b2b.com.ec/media/photo-product-olla-20.jpg",
    productUrl: "https://cocina.b2b.com.ec/products/olla-granito-20cm",
  },
  {
    ...kitchenDefaults,
    id: "prod-olla-granito-18",
    variantId: "var-olla-granito-18",
    sku: "MGC-OLLA-GRANITO-18",
    title: "Olla 18 cm Granito Premium antiadherente",
    category: "Ollas granito",
    description:
      "Olla compacta de granito antiadherente para salsas, guarniciones y porciones pequenas.",
    stock: 1,
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    pfoaFree: true,
    capacity: "1 a 2 personas",
    diameterCm: 18,
    pieces: 1,
    promoLabel: "Catalogo real WhatsApp",
    stockSignal: "Stock por confirmar por WhatsApp",
    deliveryBadge: "Envio gratis con stock confirmado",
    bundleEligible: true,
    stoveCompatibility: "Gas, induccion y vitroceramica",
    tipoCocina: "Diario ligero",
    nivel: "Uso diario",
    bundleUseCase: "Porciones pequenas, salsas, guarniciones y cocina diaria",
    careTips:
      "Cocinar a fuego medio para conservar el recubrimiento por mas tiempo.",
    healthAngle:
      "Olla compacta sin teflon para empezar con granito en la cocina diaria.",
    warrantyText: "Garantia de fabrica a confirmar por WhatsApp.",
    contentAngles: ["olla 18 cm", "tamano compacto", "uso diario en hornilla"],
    certificationStatus:
      "Catalogo WhatsApp: certificaciones USA y Europeas; guardar respaldo del proveedor antes de pauta fuerte.",
    claimNote:
      "No publicar claims medicos; libre de teflon/PFOA queda sujeto a respaldo del proveedor.",
    reorderAfterDays: 180,
    tags: ["olla", "granito", "18cm", "compacta", "menos aceite"],
    sourceUrls: ["https://wa.me/c/593979854915"],
    price: {
      amount: 63.6,
      currency: "USD",
    },
    originalPrice: {
      amount: 63.6,
      currency: "USD",
    },
    vertical: "cocina",
    brand: "Eter Niu Cocina",
    freeShipping: true,
    paymentMethods: ["transferencia", "deuna", "payphone"],
    couponCode: "GRANITOHOY",
    imageUrl: "https://cocina.b2b.com.ec/media/photo-product-olla-20.jpg",
    productUrl: "https://cocina.b2b.com.ec/products/olla-granito-18cm",
  },
  {
    ...kitchenDefaults,
    id: "prod-sarten-plano-granito-22",
    variantId: "var-sarten-plano-granito-22",
    sku: "COC-SARTEN-PLANO-GRANITO-22",
    title: "Sarten plano 22 cm Granito Premium antiadherente",
    category: "Sartenes granito",
    description:
      "Sarten plano de granito antiadherente para desayunos, vegetales y preparaciones rapidas.",
    stock: 1,
    material: "Granito antiadherente",
    coating: "Granito",
    teflonFree: true,
    pfoaFree: true,
    capacity: "1 a 3 personas",
    diameterCm: 22,
    pieces: 1,
    promoLabel: "Catalogo real WhatsApp",
    stockSignal: "Stock por confirmar por WhatsApp",
    deliveryBadge: "Envio gratis Ecuador",
    bundleEligible: true,
    stoveCompatibility: "Gas, induccion y vitroceramica",
    tipoCocina: "Rapido diario",
    nivel: "Uso diario",
    bundleUseCase: "Huevos, vegetales, pollo, tortillas y desayunos",
    careTips:
      "Usar fuego medio, utensilios suaves y evitar choque termico al lavar.",
    healthAngle:
      "Alternativa a antiadherentes tradicionales para recetas de todos los dias.",
    warrantyText: "Garantia y disponibilidad a confirmar por WhatsApp.",
    contentAngles: ["sarten 22 cm", "desayunos", "uso rapido"],
    certificationStatus:
      "Catalogo WhatsApp: certificaciones USA y Europeas; guardar respaldo del proveedor antes de pauta fuerte.",
    claimNote:
      "No publicar claims medicos; libre de teflon/PFOA queda sujeto a respaldo del proveedor.",
    reorderAfterDays: 180,
    tags: ["sarten", "granito", "22cm", "desayunos", "menos aceite"],
    sourceUrls: ["https://wa.me/c/593979854915"],
    price: {
      amount: 62.4,
      currency: "USD",
    },
    originalPrice: {
      amount: 62.4,
      currency: "USD",
    },
    vertical: "cocina",
    brand: "Eter Niu Cocina",
    freeShipping: true,
    paymentMethods: ["transferencia", "deuna", "payphone"],
    couponCode: "GRANITOHOY",
    imageUrl: "https://cocina.b2b.com.ec/media/photo-detalle-wok.jpg",
    productUrl: "https://cocina.b2b.com.ec/products/sarten-plano-granito-22cm",
  },
  {
    ...kitchenDefaults,
    id: "prod-cuchillo-samurai",
    variantId: "var-cuchillo-samurai",
    sku: "COC-CUCHILLO-SAMURAI-TODO-USO",
    title: "Cuchillo samurai Japones todo uso",
    category: "Cuchillos",
    description:
      "Cuchillo Samurai todo uso para cortes precisos en preparaciones diarias.",
    stock: 1,
    material: "Acero inoxidable",
    capacity: "Todo uso",
    pieces: 1,
    promoLabel: "Complemento",
    stockSignal: "Stock por confirmar por WhatsApp",
    deliveryBadge: "Agregar al pedido con envio gratis",
    bundleEligible: true,
    stoveCompatibility: "No aplica; complemento de cocina",
    tipoCocina: "Corte diario",
    nivel: "Uso diario",
    bundleUseCase: "Verduras, carnes, frutas y preparacion general",
    careTips: "Lavar y secar despues de usar; guardar protegido.",
    healthAngle:
      "Complemento practico para preparar ingredientes antes de cocinar.",
    warrantyText: "Garantia y disponibilidad a confirmar por WhatsApp.",
    contentAngles: ["cuchillo todo uso", "preparacion diaria"],
    certificationStatus: "No aplica",
    claimNote: "No publicar promesas de durabilidad extrema sin ficha tecnica.",
    reorderAfterDays: 240,
    tags: ["cuchillo", "samurai", "japones", "todo uso", "cocina"],
    sourceUrls: ["https://wa.me/c/593979854915"],
    price: {
      amount: 30,
      currency: "USD",
    },
    originalPrice: {
      amount: 30,
      currency: "USD",
    },
    vertical: "cocina",
    brand: "Eter Niu Cocina",
    freeShipping: true,
    paymentMethods: ["transferencia", "deuna", "payphone"],
    couponCode: "GRANITOHOY",
    imageUrl: "https://cocina.b2b.com.ec/media/photo-product-utensilios.jpg",
    productUrl:
      "https://cocina.b2b.com.ec/products/cuchillo-samurai-japones-todo-uso",
  },
];

const wellnessCatalog = [
  {
    id: "prod-juegos-de-te-aaa",
    sku: "BIEN-JUEGO-TE-AAA",
    handle: "juegos-de-te-aaa",
    title: "Juegos de te AAA",
    description:
      "Juego de te para rituales de mesa, regalos y momentos de pausa en casa.",
    category: "Hogar Zen",
    price: 139,
    material: "Ceramica y accesorios",
    capacity: "Set de te",
    image: "wellness-bowl.svg",
    tags: ["bienestar", "ritual de te", "mesa zen", "regalo premium"],
  },
  {
    id: "prod-termo-acero-sus304-500ml",
    sku: "BIEN-TERMO-SUS304-500",
    handle: "termo-acero-sus304-500ml",
    title: "Termo acero inoxidable SUS 304 500 ml",
    description:
      "Termo de acero inoxidable SUS 304 de 500 ml para agua, te o bebidas del dia.",
    category: "Hogar Zen",
    price: 20,
    material: "Acero inoxidable SUS 304",
    capacity: "500 ml",
    image: "wellness-botella.svg",
    tags: ["bienestar", "termo 500 ml", "SUS 304", "uso diario"],
  },
  {
    id: "prod-termo-acero-sus304-1000ml",
    sku: "BIEN-TERMO-SUS304-1000",
    handle: "termo-acero-sus304-1000ml",
    title: "Termo de acero SUS304 1000 ml",
    description:
      "Termo de acero SUS304 de 1000 ml para llevar bebida durante el dia.",
    category: "Hogar Zen",
    price: 28.5,
    material: "Acero inoxidable SUS 304",
    capacity: "1000 ml",
    image: "wellness-botella.svg",
    tags: ["bienestar", "termo 1000 ml", "SUS 304", "dia completo"],
  },
  {
    id: "prod-yoga-mat-suede-4mm-premium",
    sku: "BIEN-YOGA-MAT-SUEDE-4MM",
    handle: "yoga-mat-suede-4mm-premium",
    title: "Yoga Mat Suede 4 mm Premium",
    description:
      "Mat premium de suede de 4 mm para yoga, estiramiento y movimiento suave.",
    category: "Yoga & Movimiento",
    price: 79.99,
    material: "Suede",
    capacity: "Uso personal",
    image: "wellness-mat.svg",
    tags: ["bienestar", "mat suede", "4 mm", "movimiento suave"],
  },
  {
    id: "prod-meditador-mandala-pu-rubber-70cm",
    sku: "BIEN-MEDITADOR-MANDALA-70",
    handle: "meditador-mandala-pu-rubber-70cm",
    title: "Meditador Mandala PU Rubber 70 cm",
    description:
      "Meditador mandala de PU rubber de 70 cm para rincones de yoga, meditacion y pausa.",
    category: "Yoga & Movimiento",
    price: 33,
    material: "PU rubber",
    capacity: "70 cm diametro",
    image: "wellness-mat.svg",
    tags: ["bienestar", "mandala", "70 cm", "rincon de meditacion"],
  },
  {
    id: "prod-pistola-percusion-profesional-30-niveles",
    sku: "BIEN-PISTOLA-PERCUSION-PRO",
    handle: "pistola-percusion-profesional-30-niveles",
    title: "Pistola de percusion profesional 30 niveles",
    description:
      "Pistola de percusion profesional con 30 niveles para masaje muscular de rutina.",
    category: "Yoga & Movimiento",
    price: 199,
    material: "Equipo de masaje",
    capacity: "30 niveles",
    image: "wellness-mat.svg",
    tags: ["bienestar", "30 niveles", "masaje muscular", "rutina deportiva"],
  },
  {
    id: "prod-cuenco-bronce-grabado-sanscrito-8cm",
    sku: "BIEN-CUENCO-BRONCE-8",
    handle: "cuenco-bronce-grabado-sanscrito-8cm",
    title: "Cuenco de bronce con grabado sanscrito 8 cm",
    description:
      "Cuenco de bronce con grabado sanscrito de 8 cm para rituales de sonido.",
    category: "Energia & Bienestar",
    price: 45,
    material: "Bronce",
    capacity: "8 cm",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "cuenco 8 cm", "bronce", "sonido"],
  },
  {
    id: "prod-cuenco-bronce-grabado-sanscrito-9cm",
    sku: "BIEN-CUENCO-BRONCE-9",
    handle: "cuenco-bronce-grabado-sanscrito-9cm",
    title: "Cuenco de bronce con grabado sanscrito 9 cm",
    description:
      "Cuenco de bronce con grabado sanscrito de 9 cm para rituales de sonido.",
    category: "Energia & Bienestar",
    price: 65,
    material: "Bronce",
    capacity: "9 cm",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "cuenco 9 cm", "bronce", "sonido"],
  },
  {
    id: "prod-tambor-lengua-8-notas",
    sku: "BIEN-TAMBOR-LENGUA-8-NOTAS",
    handle: "tambor-lengua-8-notas",
    title: "Tambor de lengua 8 notas",
    description:
      "Tambor de lengua de 8 notas para sonido ambiental, regalos y pausas personales.",
    category: "Energia & Bienestar",
    price: 65,
    material: "Metal",
    capacity: "8 notas",
    image: "wellness-tambor-lengua-real.jpg",
    tags: ["bienestar", "8 notas", "sonido", "regalo"],
  },
  {
    id: "prod-argollas-plata-925",
    sku: "BIEN-ARGOLLAS-PLATA-925",
    handle: "argollas-plata-925",
    title: "Argollas plata 925",
    description: "Argollas de plata 925 para uso diario o regalo especial.",
    category: "Tesoros Plata & Acero",
    price: 43,
    material: "Plata 925",
    capacity: "Uso personal",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "plata 925", "regalo", "uso diario"],
  },
  {
    id: "prod-dije-om-grande",
    sku: "BIEN-DIJE-OM-PLATA-925",
    handle: "dije-om-grande",
    title: "Dije OM grande",
    description:
      "Dije OM grande para regalo, uso personal o practica espiritual.",
    category: "Tesoros Plata & Acero",
    price: 74,
    material: "Plata 925 por confirmar",
    capacity: "Dije grande",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "simbolo OM", "regalo", "accesorio espiritual"],
  },
  {
    id: "prod-amuleto-hindu-plata-925",
    sku: "BIEN-AMULETO-HINDU-PLATA-925",
    handle: "amuleto-hindu-plata-925",
    title: "Amuleto Hindu plata 925",
    description: "Amuleto hindu de plata 925 para uso personal o regalo.",
    category: "Tesoros Plata & Acero",
    price: 38,
    material: "Plata 925",
    capacity: "Amuleto",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "amuleto", "plata 925", "regalo"],
  },
  {
    id: "prod-cascadas-humo-om-ganesha-torre",
    sku: "BIEN-CASCADA-HUMO-OM-GANESHA-TORRE",
    handle: "cascadas-humo-om-ganesha-torre",
    title: "Cascadas de humo OM, Ganesha y Torre",
    description:
      "Cascadas de humo con disenos OM, Ganesha y Torre para ambientar espacios.",
    category: "Energia & Bienestar",
    price: 12,
    material: "Accesorio decorativo",
    capacity: "1 cascada",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "humo", "OM", "Ganesha"],
  },
  {
    id: "prod-pendulo-7-chakras",
    sku: "BIEN-PENDULO-7-CHAKRAS",
    handle: "pendulo-7-chakras",
    title: "Pendulo 7 chakras",
    description:
      "Pendulo 7 chakras para practica personal y accesorios energeticos.",
    category: "Energia & Bienestar",
    price: 13.33,
    material: "Piedras y metal por confirmar",
    capacity: "Uso personal",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "7 chakras", "pendulo", "regalo pequeno"],
  },
  {
    id: "prod-lampara-sal-himalaya-10kg-grande",
    sku: "BIEN-LAMPARA-SAL-HIMALAYA-10KG",
    handle: "lampara-sal-himalaya-10kg-grande",
    title: "Lampara de sal Himalaya 10 kilos grande",
    description:
      "Lampara de sal Himalaya grande de 10 kilos para luz calida y decoracion.",
    category: "Energia & Bienestar",
    price: 65,
    material: "Sal del Himalaya",
    capacity: "10 kilos",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "10 kilos", "luz calida", "decoracion"],
  },
  {
    id: "prod-moxas-chinas",
    sku: "BIEN-MOXAS-CHINAS",
    handle: "moxas-chinas",
    title: "Moxas Chinas",
    description:
      "Moxas chinas para practica personal supervisada y rituales tradicionales.",
    category: "Energia & Bienestar",
    price: 20,
    material: "Moxa por confirmar",
    capacity: "Set de moxas",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "moxas", "tradicion", "ritual"],
  },
  {
    id: "prod-bloques-yoga-3-capas",
    sku: "BIEN-BLOQUES-YOGA-3-CAPAS",
    handle: "bloques-yoga-3-capas",
    title: "Bloques de yoga 3 capas",
    description:
      "Bloque de yoga de 3 capas para soporte en posturas y estiramiento.",
    category: "Yoga & Movimiento",
    price: 15,
    material: "EVA por confirmar",
    capacity: "1 bloque",
    image: "wellness-mat.svg",
    tags: ["bienestar", "bloque yoga", "soporte", "movimiento"],
  },
  {
    id: "prod-portaincienso-horizontal-madera",
    sku: "BIEN-PORTAINCIENSO-HORIZONTAL-MADERA",
    handle: "portaincienso-horizontal-madera",
    title: "Portaincienso horizontal de madera",
    description:
      "Portaincienso horizontal de madera para rutinas de aroma y decoracion.",
    category: "Energia & Bienestar",
    price: 12,
    material: "Madera",
    capacity: "1 portaincienso",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "incienso", "madera", "decoracion"],
  },
  {
    id: "prod-cadena-hombre-rasgado",
    sku: "BIEN-CADENA-HOMBRE-RASGADO",
    handle: "cadena-hombre-rasgado",
    title: "Cadena hombre rasgado",
    description:
      "Cadena de hombre estilo rasgado para uso personal o regalo premium.",
    category: "Tesoros Plata & Acero",
    price: 350,
    material: "Metal por confirmar",
    capacity: "Cadena",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "cadena", "hombre", "regalo premium"],
  },
  {
    id: "prod-dijes-animales-galapagos-plata-925",
    sku: "BIEN-DIJES-ANIMALES-GALAPAGOS-PLATA-925",
    handle: "dijes-animales-galapagos-plata-925",
    title: "Dijes Animales Galapagos plata 925",
    description:
      "Dijes de animales Galapagos en plata 925 para regalo y uso personal.",
    category: "Tesoros Plata & Acero",
    price: 15,
    material: "Plata 925 por confirmar",
    capacity: "Dije",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "galapagos", "dije", "regalo"],
  },
  {
    id: "prod-portaincienso-metal",
    sku: "BIEN-PORTAINCIENSO-METAL",
    handle: "portaincienso-metal",
    title: "Portaincienso metal",
    description: "Portaincienso de metal para aroma, decoracion y uso diario.",
    category: "Energia & Bienestar",
    price: 15,
    material: "Metal",
    capacity: "1 portaincienso",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "incienso", "metal", "decoracion"],
  },
  {
    id: "prod-portaincienso-vertical-bronce",
    sku: "BIEN-PORTAINCIENSO-VERTICAL-BRONCE",
    handle: "portaincienso-vertical-bronce",
    title: "Portaincienso vertical de bronce",
    description:
      "Portaincienso vertical de bronce para rincones de aroma y decoracion.",
    category: "Energia & Bienestar",
    price: 29.99,
    material: "Bronce",
    capacity: "1 portaincienso",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "incienso", "bronce", "decoracion"],
  },
  {
    id: "prod-saumador-palo-santo-bronce",
    sku: "BIEN-SAUMADOR-PALO-SANTO-BRONCE",
    handle: "saumador-palo-santo-bronce",
    title: "Saumador de palo Santo en bronce",
    description: "Saumador de bronce para palo santo, aroma y decoracion.",
    category: "Energia & Bienestar",
    price: 39.99,
    material: "Bronce",
    capacity: "1 saumador",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "palo santo", "bronce", "aroma"],
  },
  {
    id: "prod-aretes-acero-inoxidable",
    sku: "BIEN-ARETES-ACERO-INOXIDABLE",
    handle: "aretes-acero-inoxidable",
    title: "Aretes acero inoxidable",
    description: "Aretes de acero inoxidable para uso diario y regalo.",
    category: "Tesoros Plata & Acero",
    price: 15,
    material: "Acero inoxidable",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes", "acero inoxidable", "regalo"],
  },
  {
    id: "prod-aretes-plata-925",
    sku: "BIEN-ARETES-PLATA-925",
    handle: "aretes-plata-925",
    title: "Aretes Plata 925",
    description: "Aretes de plata 925 para uso diario o regalo especial.",
    category: "Tesoros Plata & Acero",
    price: 33,
    material: "Plata 925",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes", "plata 925", "regalo"],
  },
  {
    id: "prod-argollas-plata-925-2999",
    sku: "BIEN-ARGOLLAS-PLATA-925-2999",
    handle: "argollas-plata-925-2999",
    title: "Argollas de Plata 925",
    description: "Argollas de plata 925 para uso diario o regalo.",
    category: "Tesoros Plata & Acero",
    price: 29.99,
    material: "Plata 925",
    capacity: "Par de argollas",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "argollas", "plata 925", "regalo"],
  },
  {
    id: "prod-anillos-hombre-acero-inoxidable",
    sku: "BIEN-ANILLOS-HOMBRE-ACERO",
    handle: "anillos-hombre-acero-inoxidable",
    title: "Anillos hombre Acero Inoxidable",
    description: "Anillos de hombre en acero inoxidable para uso diario.",
    category: "Tesoros Plata & Acero",
    price: 19.99,
    material: "Acero inoxidable",
    capacity: "1 anillo",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "anillos hombre", "acero inoxidable", "regalo"],
  },
  {
    id: "prod-anillos-acero-inoxidable-mujer-ajustables",
    sku: "BIEN-ANILLOS-MUJER-ACERO-AJUSTABLES",
    handle: "anillos-acero-inoxidable-mujer-ajustables",
    title: "Anillos Acero Inoxidable mujer ajustables",
    description: "Anillos ajustables de acero inoxidable para mujer.",
    category: "Tesoros Plata & Acero",
    price: 9.99,
    material: "Acero inoxidable",
    capacity: "1 anillo ajustable",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "anillos mujer", "ajustables", "acero inoxidable"],
  },
  {
    id: "prod-dije-om-acero-inoxidable",
    sku: "BIEN-DIJE-OM-ACERO",
    handle: "dije-om-acero-inoxidable",
    title: "Dije OM Acero inoxidable",
    description:
      "Dije OM de acero inoxidable para accesorio personal o regalo pequeno.",
    category: "Tesoros Plata & Acero",
    price: 5,
    material: "Acero inoxidable",
    capacity: "Dije",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "OM", "acero inoxidable", "regalo pequeno"],
  },
  {
    id: "prod-aretes-largos-acero-inoxidable-plateados",
    sku: "BIEN-ARETES-LARGOS-ACERO-PLATEADOS",
    handle: "aretes-largos-acero-inoxidable-plateados",
    title: "Aretes largos Acero inoxidable plateados",
    description:
      "Aretes largos plateados de acero inoxidable para regalo o uso personal.",
    category: "Tesoros Plata & Acero",
    price: 19.99,
    material: "Acero inoxidable",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes largos", "plateados", "acero inoxidable"],
  },
  {
    id: "prod-aretes-largos-acero-inoxidable-dorados",
    sku: "BIEN-ARETES-LARGOS-ACERO-DORADOS",
    handle: "aretes-largos-acero-inoxidable-dorados",
    title: "Aretes largos Acero inoxidable dorados",
    description:
      "Aretes largos dorados de acero inoxidable para regalo o uso personal.",
    category: "Tesoros Plata & Acero",
    price: 19.99,
    material: "Acero inoxidable",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes largos", "dorados", "acero inoxidable"],
  },
  {
    id: "prod-aretes-acero-inoxidable-oro-rosado",
    sku: "BIEN-ARETES-ACERO-ORO-ROSADO",
    handle: "aretes-acero-inoxidable-oro-rosado",
    title: "Aretes Acero Inoxidable oro rosado",
    description: "Aretes color oro rosado de acero inoxidable para uso diario.",
    category: "Tesoros Plata & Acero",
    price: 15,
    material: "Acero inoxidable",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes", "oro rosado", "acero inoxidable"],
  },
  {
    id: "prod-aretes-pequenos-acero-inoxidable",
    sku: "BIEN-ARETES-PEQUENOS-ACERO",
    handle: "aretes-pequenos-acero-inoxidable",
    title: "Aretes pequenos Acero inoxidable",
    description: "Aretes pequenos de acero inoxidable para uso diario.",
    category: "Tesoros Plata & Acero",
    price: 9.99,
    material: "Acero inoxidable",
    capacity: "Par de aretes",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "aretes pequenos", "acero inoxidable", "regalo"],
  },
  {
    id: "prod-collares-quarzos-naturales",
    sku: "BIEN-COLLARES-QUARZOS-NATURALES",
    handle: "collares-quarzos-naturales",
    title: "Collares de Quarzos Naturales",
    description:
      "Collares de quarzos naturales para accesorio personal o regalo.",
    category: "Tesoros Plata & Acero",
    price: 19.99,
    material: "Quarzos naturales por confirmar",
    capacity: "1 collar",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "quarzos", "collar", "regalo"],
  },
  {
    id: "prod-velas-grandes-caja-mandala",
    sku: "BIEN-VELAS-GRANDES-CAJA-MANDALA",
    handle: "velas-grandes-caja-mandala",
    title: "Velas grandes caja mandala",
    description: "Velas grandes en caja mandala para ambientar espacios.",
    category: "Energia & Bienestar",
    price: 4.99,
    material: "Cera por confirmar",
    capacity: "Caja mandala",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "velas", "mandala", "decoracion"],
  },
  {
    id: "prod-velas-pequenas-caja-mandala",
    sku: "BIEN-VELAS-PEQUENAS-CAJA-MANDALA",
    handle: "velas-pequenas-caja-mandala",
    title: "Velas pequenas caja mandala",
    description: "Velas pequenas en caja mandala para ambientar espacios.",
    category: "Energia & Bienestar",
    price: 3.99,
    material: "Cera por confirmar",
    capacity: "Caja mandala",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "velas pequenas", "mandala", "decoracion"],
  },
  {
    id: "prod-piedra-alumbre",
    sku: "BIEN-PIEDRA-ALUMBRE",
    handle: "piedra-alumbre",
    title: "Piedra Alumbre",
    description:
      "Piedra alumbre para rutina de cuidado personal, segun uso tradicional.",
    category: "Cuidado Personal",
    price: 5,
    material: "Alumbre",
    capacity: "1 piedra",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "alumbre", "cuidado personal", "rutina"],
  },
  {
    id: "prod-lampara-ghee-bronce-100",
    sku: "BIEN-LAMPARA-GHEE-BRONCE",
    handle: "lampara-ghee-bronce-100",
    title: "Lampara de ghee Bronce 100%",
    description:
      "Lampara de ghee de bronce para ritual, decoracion y ambiente.",
    category: "Energia & Bienestar",
    price: 11,
    material: "Bronce",
    capacity: "1 lampara",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "ghee", "bronce", "ritual"],
  },
  {
    id: "prod-nataraj-bronce",
    sku: "BIEN-NATARAJ-BRONCE",
    handle: "nataraj-bronce",
    title: "Nataraj Bronce",
    description:
      "Figura Nataraj de bronce para decoracion y espacios de pausa.",
    category: "Energia & Bienestar",
    price: 55,
    material: "Bronce",
    capacity: "Figura decorativa",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "nataraj", "bronce", "decoracion"],
  },
  {
    id: "prod-inciensos-stick-jumbo",
    sku: "BIEN-INCIENSOS-STICK-JUMBO",
    handle: "inciensos-stick-jumbo",
    title: "Inciensos Stick Jumbo",
    description: "Inciensos stick jumbo para aroma y ambiente en casa.",
    category: "Energia & Bienestar",
    price: 4.99,
    material: "Incienso",
    capacity: "Stick jumbo",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "incienso jumbo", "aroma", "ambiente"],
  },
  {
    id: "prod-straps-18-metros",
    sku: "BIEN-STRAP-1-8M",
    handle: "straps-18-metros",
    title: "Straps 1.8 metros",
    description:
      "Strap de 1.8 metros para yoga, estiramiento y movilidad suave.",
    category: "Yoga & Movimiento",
    price: 9,
    material: "Tela por confirmar",
    capacity: "1.8 metros",
    image: "wellness-mat.svg",
    tags: ["bienestar", "strap 1.8 m", "yoga", "movimiento"],
  },
  {
    id: "prod-straps-3-metros",
    sku: "BIEN-STRAP-3M",
    handle: "straps-3-metros",
    title: "Straps 3 metros",
    description: "Strap de 3 metros para yoga, estiramiento y movilidad suave.",
    category: "Yoga & Movimiento",
    price: 11,
    material: "Tela por confirmar",
    capacity: "3 metros",
    image: "wellness-mat.svg",
    tags: ["bienestar", "strap 3 m", "yoga", "movimiento"],
  },
  {
    id: "prod-limpiador-lengua-cobre-100-virgen",
    sku: "BIEN-LIMPIADOR-LENGUA-COBRE",
    handle: "limpiador-lengua-cobre-100-virgen",
    title: "Limpiador de Lengua Cobre 100% Virgen hecho a mano",
    description:
      "Limpiador de lengua de cobre hecho a mano para rutina diaria de cuidado personal.",
    category: "Cuidado Personal",
    price: 15,
    material: "Cobre",
    capacity: "1 limpiador",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "limpiador lengua", "cobre", "rutina diaria"],
  },
  {
    id: "prod-tetera-vidrio-450ml",
    sku: "BIEN-TETERA-VIDRIO-450",
    handle: "tetera-vidrio-450ml",
    title: "Tetera vidrio 450 ml",
    description:
      "Tetera de vidrio de 450 ml para infusiones y rituales de mesa.",
    category: "Hogar Zen",
    price: 15,
    material: "Vidrio",
    capacity: "450 ml",
    image: "wellness-bowl.svg",
    tags: ["bienestar", "tetera 450 ml", "vidrio", "infusiones"],
  },
  {
    id: "prod-incienso-organicos-ullas-hechos-a-mano",
    sku: "BIEN-INCIENSO-ORGANICOS-ULLAS",
    handle: "incienso-organicos-ullas-hechos-a-mano",
    title: "Incienso Organicos Ullas hechos a mano",
    description:
      "Inciensos organicos Ullas hechos a mano para aroma y ambiente.",
    category: "Energia & Bienestar",
    price: 4.99,
    material: "Incienso organico por confirmar",
    capacity: "Caja de incienso",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "incienso organico", "hecho a mano", "ambiente"],
  },
  {
    id: "prod-tetera-vidrio-1600ml-infusor",
    sku: "BIEN-TETERA-VIDRIO-1600-INFUSOR",
    handle: "tetera-vidrio-1600ml-infusor",
    title: "Tetera vidrio 1600 ml con infusor",
    description:
      "Tetera de vidrio de 1600 ml con infusor para compartir infusiones.",
    category: "Hogar Zen",
    price: 15,
    material: "Vidrio",
    capacity: "1600 ml",
    image: "wellness-bowl.svg",
    tags: ["bienestar", "tetera 1600 ml", "infusor", "vidrio"],
  },
  {
    id: "prod-bolsters-cuadrados",
    sku: "BIEN-BOLSTERS-CUADRADOS",
    handle: "bolsters-cuadrados",
    title: "Bolsters cuadrados",
    description:
      "Bolster cuadrado para apoyo en yoga, descanso y estiramiento suave.",
    category: "Yoga & Movimiento",
    price: 35,
    material: "Textil por confirmar",
    capacity: "1 bolster",
    image: "wellness-mat.svg",
    tags: ["bienestar", "bolster", "yoga", "descanso"],
  },
  {
    id: "prod-juegos-de-te-japoneses",
    sku: "BIEN-JUEGOS-TE-JAPONESES",
    handle: "juegos-de-te-japoneses",
    title: "Juegos de te Japoneses",
    description: "Juego de te japones para mesa, regalos y pausas en casa.",
    category: "Hogar Zen",
    price: 39.99,
    material: "Ceramica por confirmar",
    capacity: "Set de te",
    image: "wellness-bowl.svg",
    tags: ["bienestar", "te japones", "set de te", "regalo"],
  },
  {
    id: "prod-billete-1-millon",
    sku: "BIEN-BILLETE-1-MILLON",
    handle: "billete-1-millon",
    title: "Billete 1 Millon",
    description:
      "Billete decorativo de 1 millon para regalo simbolico o detalle.",
    category: "Energia & Bienestar",
    price: 3.5,
    material: "Papel decorativo",
    capacity: "1 billete",
    image: "wellness-aroma.svg",
    tags: ["bienestar", "billete 1 millon", "detalle", "regalo"],
  },
] as const;

const wellnessProducts: Product[] = wellnessCatalog.map((product) => ({
  ...wellnessDefaults,
  id: product.id,
  variantId: product.id.replace("prod-", "var-"),
  sku: product.sku,
  title: product.title,
  description: product.description,
  category: product.category,
  price: { amount: product.price, currency: "USD" },
  promoLabel: product.category,
  stockSignal: "Stock por confirmar por WhatsApp",
  bundleEligible: true,
  material: product.material,
  capacity: product.capacity,
  pieces: 1,
  nivel: product.category,
  bundleUseCase: product.description,
  careTips: "Confirmar cuidados y disponibilidad por WhatsApp.",
  healthAngle: "Producto de bienestar sin promesas medicas ni terapeuticas.",
  warrantyText: "Garantia y disponibilidad a confirmar por WhatsApp.",
  sourceUrls: ["https://wa.me/c/593979854915"],
  contentAngles: product.tags.slice(1, 4),
  certificationStatus: "Proveedor por confirmar",
  claimNote:
    "No publicar claims medicos, terapeuticos o espirituales absolutos.",
  reorderAfterDays: 180,
  stock: 1,
  imageUrl: `https://bienestar.b2b.com.ec/media/${product.image}`,
  productUrl: `https://bienestar.b2b.com.ec/campanas/${product.handle}?sku=${product.sku}`,
  tags: [...product.tags],
}));

export const demoCatalog: Product[] = [...kitchenCatalog, ...wellnessProducts];
